# Generated by Django 3.0a1 on 2019-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('DJ', 'Django'), ('NG', 'Angular'), ('RE', 'React')], default='DJ', max_length=10)),
            ],
        ),
    ]
