# Generated by Django 3.0a1 on 2019-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdevelopment',
            name='framework',
            field=models.CharField(choices=[('DJ', 'Django'), ('NG', 'Angular'), ('RE', 'React')], default='DJ', max_length=2),
        ),
    ]
